core/urls.py
from django.conf.urls import url

from . import views

# Application Routes (URLs)

app_name = 'core'

urlpatterns = [

	# Login
	url(r'^login/$', views.login, name='login'),

	# Logout
	url(r'^logout/$', views.logout, name='logout'),
]

management/urls.py
from django.conf.urls import url, include

from . import views
from management.views import (upload_csv, UpdateLenseModelsView)

# Application Routes (URLs)

app_name = 'management'

urlpatterns = [
    	# General Page Views
		url(r'^upload/csv/$', upload_csv, name='upload_csv'),
		url(r'^update-lense-models/$', UpdateLenseModelsView.as_view(), name='update_lense_models'),
		url(r'^toggle-cnc/$', views.cnc_toggle_lock_view, name='toggle_cnc'),
		url(r'^get-task/$', views.get_cnc_task_view, name='get_task'),
		url(r'^cut/(?P<pk>\d+)/$', views.cut_view, name='cut'),
		url(r'^stop-cnc/$', views.stop_cnc_view, name='stop_cnc'),
]

reporting/urls.py
from django.conf.urls import url, include


from .views import HomePageView

# Application Routes (URLs)

app_name = 'reporting'

urlpatterns = [
    	# General Page Views
		url(r'^$', HomePageView.as_view(), name='homepage'),
]

website/urls.py
from django.conf.urls import url, include

from . import views

# Application Routes (URLs)

app_name = 'website'

urlpatterns = [
    	# General Page Views
		url(r'^$', views.homepage_view, name='homepage'),
		url(r'^add-to-queue$', views.add_to_queue_view, name='add_to_queue'),
		url(r'^copy-item/(?P<pk>\d+)/$', views.copy_item_view, name='copy_item'),
		url(r'^delete-from-queue/(?P<pk>\d+)/$', views.delete_from_queue_view, name='delete_from_queue'),
		url(r'^change-model$', views.change_model_view, name='change_model'),
		url(r'^save-queue$', views.save_queue_view, name='save_queue'),
		url(r'^add-bands-from-queue/(?P<pk>\d+)/$', views.add_bands_from_queue_view, name='add_bands_from_queue'),
		url(r'^delete-saved-queue/(?P<pk>\d+)/$', views.delete_saved_queue_view, name='delete_saved_queue'),
]

management/models.py
from django.db import models

from django.contrib.auth.models import User

name_length = 100
decimal_digits = 2
max_digits = 6

class StandardBandit(models.Model):
    name = models.CharField(max_length=name_length)
    abbreviation = models.CharField(max_length=3, unique=True)
    initial_height = models.DecimalField(default=0, max_digits=max_digits, decimal_places=decimal_digits)

    def __str__(self):
        return str(self.abbreviation)

class Lense(models.Model):
    make = models.CharField(max_length=name_length)
    model = models.CharField(max_length=name_length)
    diameter = models.DecimalField(default=0, max_digits=max_digits, decimal_places=decimal_digits)
    height = models.DecimalField(default=0, max_digits=max_digits, decimal_places=decimal_digits)
    type = models.CharField(max_length=5)
    custom_band_size = models.ForeignKey(StandardBandit, blank=True, null=True, on_delete=models.SET_NULL)
    amount_processed = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.make) + ' | ' + str(self.model) + ' | ' + str(self.type)

    def findSizePart2(self):
        sizePart2 = ""
        height = self.height
        if height <= 30:
            sizePart2 = "s"
        elif height >= 31 and height <= 42:
            sizePart2 = "m"
        else:
            sizePart2 = "l"
        return sizePart2

    def get_band_size(self):
        if self.custom_band_size:
            return self.custom_band_size

        sizePart1, sizePart2 = "", ""

        if self.diameter <= 75:
            if self.diameter >= 70 and self.height > 20:
                sizePart1 = "M"
                sizePart2 = self.findSizePart2()
            else:
                sizePart1 = "S"

        elif self.diameter >= 76 and self.diameter <= 93:
            sizePart1 = "M"
            sizePart2 = self.findSizePart2()

        else:
            sizePart1 = "L"

        return StandardBandit.objects.get(abbreviation=sizePart1 + sizePart2)


class Setting(models.Model):
    small_plunge_distance = models.DecimalField(default=0, max_digits=max_digits, decimal_places=decimal_digits)
    medium_plunge_distance = models.DecimalField(default=0, max_digits=max_digits, decimal_places=decimal_digits)
    large_plunge_distance = models.DecimalField(default=0, max_digits=max_digits, decimal_places=decimal_digits)
    cnc_is_locked = models.BooleanField(default=False)
    recent_orders_to_retain = models.PositiveIntegerField(default=0)
    cnc_task = models.ForeignKey('website.LenseInQueue', blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return "System Settings"

website/models.py
from django.db import models

from django.contrib.auth.models import User

from management.models import Lense

class LenseInQueue(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    lense = models.ForeignKey(Lense, on_delete=models.CASCADE)

    def __str__(self):
        return "Lense Queue for " + str(self.user)

class SavedQueue(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_items_in_queue(self):
        return SavedQueueItem.objects.filter(queue=self)

class SavedQueueItem(models.Model):
    queue = models.ForeignKey(SavedQueue, on_delete=models.CASCADE)
    lense = models.ForeignKey(Lense, on_delete=models.CASCADE)

    def __str__(self):
        return "Lense Queue for " + str(self.user)

website/forms.py
from django import forms

from management.models import Lense, StandardBandit

type_choices = (
    ("zoom", "zoom"),
    ("focus", "focus"),
)

class SaveQueueForm(forms.Form):
    name = forms.CharField(max_length=100)

class QueueForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(QueueForm, self).__init__(*args, **kwargs)
        makes = Lense.objects.all().values_list('make', flat=True).distinct()
        make_choices = [(make, make) for make in makes]
        self.fields['make'] = forms.ChoiceField(choices=make_choices)

        models = Lense.objects.all().values_list('model', flat=True).distinct()
        model_choices = [(model, model) for model in models]
        self.fields['model'] = forms.ChoiceField(choices=model_choices)

        self.fields['type'] = forms.ChoiceField(choices=type_choices)
        self.fields['custom_size'] = forms.ModelChoiceField(queryset=StandardBandit.objects.all(), required=False)

    def clean(self):
        data = self.cleaned_data
        if not len(Lense.objects.filter(make=data['make'], model=data['model'], type=data['type'])) == 1:
            raise forms.ValidationError({"type": "Error, this lense does not have this type!"})

website/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.contrib import messages
from django.shortcuts import render, redirect
from django.template.loader import render_to_string

from management.models import Lense

from .forms import QueueForm, SaveQueueForm

from .utils import add_to_queue

from .models import LenseInQueue, SavedQueue, SavedQueueItem

import json

@login_required
def homepage_view(request):
    context = {
    "form" : QueueForm(),
    "queue" : LenseInQueue.objects.filter(user=request.user),
    'save_form' : SaveQueueForm(),
    'saved_queues' : SavedQueue.objects.filter(user=request.user)
    }
    return render(request, "website/homepage.html", context)

@login_required
def change_model_view(request):
    make = request.GET['make']
    form = QueueForm()
    print("Make: " + make)
    form.fields['make'].initial = make

    models = Lense.objects.filter(make=make).values_list('model', flat=True).distinct()
    model_choices = [(model, model) for model in models]
    form.fields['model'].choices = model_choices
    context = {"form" : form}
    return JsonResponse({"new_form": render_to_string('website/queue_form.html', request=request, context=context)})

@login_required
def add_to_queue_view(request):
    if request.method == "POST":
        form = QueueForm(request.POST)

        if not form.is_valid():
            context = {
            "form" : form,
            "queue" : LenseInQueue.objects.filter(user=request.user)
            }
            return render(request, 'website/homepage.html', context)

        add_to_queue(request.user, form.cleaned_data)
    return redirect('website:homepage')

@login_required
def copy_item_view(request, pk):
    try:
        item = LenseInQueue.objects.get(pk=pk)
        LenseInQueue.objects.create(user=item.user, lense=item.lense)
    except:
        pass
    return redirect('website:homepage')

@login_required
def delete_from_queue_view(request, pk):
    try:
        item = LenseInQueue.objects.get(pk=pk)
        if request.user == item.user:
            item.delete()
    except:
        pass
    return redirect('website:homepage')

@login_required
def save_queue_view(request):
    if request.method == "POST":
        form = SaveQueueForm(request.POST)
        if form.is_valid():
            lenses_in_queue = LenseInQueue.objects.filter(user=request.user)
            sq = SavedQueue()
            sq.name = form.cleaned_data['name']
            sq.user = request.user
            sq.save()
            for item in lenses_in_queue:
                SavedQueueItem.objects.create(lense=item.lense, queue=sq)
            messages.success(request, "Queue saved!")
    return redirect('website:homepage')

@login_required
def add_bands_from_queue_view(request, pk):
    sq = SavedQueue.objects.get(pk=pk)
    for item in SavedQueueItem.objects.filter(queue=sq):
        LenseInQueue.objects.create(user=request.user, lense=item.lense)
    return redirect('website:homepage')

@login_required
def delete_saved_queue_view(request, pk):
    if SavedQueue.objects.filter(pk=pk, user=request.user).exists():
        SavedQueue.objects.get(pk=pk).delete()
    return redirect('website:homepage')

website/templates/website/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">


		<title>{% block title %}RDM CNC Software{% endblock title %}</title>

		<!-- CSS -->
			<!-- Latest compiled and minified CSS -->
			<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
			<link rel="stylesheet" href="{% static 'website/css/bootstrap.min.css' %}">
			<link rel="stylesheet" href="{% static 'website/css/animate.css' %}"/>
			<link rel="stylesheet" href="{% static 'website/css/style.css' %}"/>
			{% block custom_css %}
			{% endblock custom_css %}

		<!-- JavaScript -->

			<!-- jQuery library -->
			<script src="{% static 'website/js/jquery.min.js' %}"></script>

			<!-- Latest compiled JavaScript -->
			<script src="{% static 'website/js/bootstrap.min.js' %}"></script>

			<script src="{% static 'website/js/main.js' %}"></script>

			{% block head_js %}
			{% endblock head_js %}

	</head>
	<body>

		{% include 'website/navbar.html' %}

		{% block content %}
		{% endblock content %}

		{% block js %}
		{% endblock js %}
	</body>
</html>

website/templates/website/homepage.html
{% extends 'website/base.html' %}

{% block custom_css %}
<style type="text/css">
body {
  background-color: #f5f6f7;
}

h2 {
  text-align: center;
}

.heading {
  background-color: #08f;
  color: white;
  text-align: center;
  font-weight: bold;
  font-size: 25px;
}

.right {
  text-align: right;
  float: right;
}

select {
  margin-bottom: 25px;
}

td, tr {
  background-color: white;
}

.fa-copy {
  color: orange;
}

.queue > tbody > tr > td:nth-child(odd):hover {
  background-color: #ddd;
  cursor: pointer;
}

.saved:hover {
  background-color: #ddd;
  cursor: pointer;
}

.saved {
  border-top-left-radius: 10px !important;
  border-top-right-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
  border-bottom-right-radius: 10px !important;
}

.save-queue {
  -webkit-box-shadow: 0px 2px 5px 2px rgba(168,168,168,1);
  -moz-box-shadow: 0px 2px 5px 2px rgba(168,168,168,1);
  box-shadow: 0px 2px 5px 2px rgba(168,168,168,1);
  background-color:white;padding:20px;padding-bottom:8px;border-radius:10px;
}
</style>
{% endblock custom_css %}

{% block content %}
{% include 'website/server_messages.html' %}
<br />
<div class="container">
  <div class="row">
      <div class="col-lg-4">
        <h2>Add to Queue</h2>
          <table class="table">
              <tbody>
                  <tr>
                    <td class="heading top-rounded">
                      Select a Lense
                    </td>
                  </tr>
                  <tr>
                    <td id="form-container" class="content">
                      {% include 'website/queue_form.html' %}
                    </td>
                  </tr>
                  <tr>
                      <td class="heading">
                        Recent Lenses
                      </td>
                  </tr>
                  <tr>
                    <td class="content bottom-rounded">
                      {% for lense in recent_lenses %}
                      {% empty %}
                        There are no recent lenses
                      {% endfor %}
                    </td>
                  </tr>
              </tbody>
          </table>
      </div>
      <div class="col-lg-4">
          <h2>Saved Queues</h2>
          <table class="table">
              <tbody>
                {% for queue in saved_queues %}
                <tr>
                  <td href="{% url 'website:add_bands_from_queue' pk=queue.pk %}" class="saved">
                    <b>Name:</b> {{ queue.name }}
                    <i href="{% url 'website:delete_saved_queue' pk=queue.pk %}" class="fas fa-trash-alt" data-toggle="tooltip" title="Deleted this saved queue" style="float:right;"></i>
                    <ul>
                      {% for item in queue.get_items_in_queue %}
                      <li>
                        {{ item.lense }}
                      </li>
                      {% empty %}
                      <li>
                        This queue has no lenses
                      </li>
                      {% endfor %}
                    </ul>
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td class="bottom-rounded top-rounded">
                    You have no save queues.
                  </td>
                </tr>
                {% endfor %}
              </tbody>
          </table>
      </div>
      <div class="col-lg-4">
          <h2>Current Queue</h2>
          <table class="table queue">
              <tbody>
                {% for item in queue %}
                <tr>
                  <td href="{% url 'management:cut' pk=item.pk %}" class="bottom-rounded top-rounded">
                    {{ item.lense.make }} | {{ item.lense.model }} | <text style="color:#08f;">{{ item.lense.type }}</text><br />
                    Band Size Needed: <text style="color:#08f;">{{ item.lense.get_band_size }}</text>
                  </td>
                  <td class="bottom-rounded top-rounded">
                    <i href="{% url 'website:delete_from_queue' pk=item.pk %}" class="fas fa-trash-alt"></i><br />
                    <i href="{% url 'website:copy_item' pk=item.pk %}" class="far fa-copy"></i>
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="2" class="bottom-rounded top-rounded">
                    There are no lenses currently in the Queue
                  </td>
                </tr>
                {% endfor %}
              </tbody>
          </table>
          <hr />
          <div class="save-queue">
            <h2>Save this queue</h2>
            <form action="{% url 'website:save_queue' %}" method="POST">
              {% csrf_token %}
              {% for field in save_form %}
              <b>Name to save as</b>
              {{ field }}
              {% endfor %}
              <br /><br />
              <button class="btn btn-warning" style="float:right;">Save Current Queue</button>
              <br /><br />
            </form>
          </div>
      </div>
  </div>
</div>
{% endblock content %}

{% block js %}
<script>
  $(".queue > tbody > tr > td:nth-child(odd)").click(function() {
      window.location.href = $(this).attr('href');
  });

  $('.fa-copy').click(function() {
      window.location.href = $(this).attr('href');
  });

  $(".fa-trash-alt").click(function(e) {
      e.stopPropagation();
      window.location.href = $(this).attr('href');
  });

  $('.saved').click(function() {
      window.location.href = $(this).attr('href');
  });

  // Dynamically update the models of queue form
  $('body').on('change', '#id_make', function() {
      $.get("{% url 'website:change_model' %}", {
        "make": $(this).val()
      }, function(data) {
        $('#form-container').html(data.new_form);
        console.log("data: " + data.new_form + "\n\n");
      });
  });
</script>
{% endblock js %}

website/templates/website/navbar.html
{% load staticfiles %}

<style type="text/css">
  .lock:hover .fa-unlock,
  .lock .fa-lock {
      display: none;
  }
  .lock:hover .fa-lock {
      display: inline;
  }
  .unlock:hover .fa-lock,
  .unlock .fa-unlock {
      display: none;
  }
  .unlock:hover .fa-unlock {
      display: inline;
  }
</style>



<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="{% url 'website:homepage' %}">
    <img id="logo" src="{% static 'website/images/logo.jpg' %}" alt="Logo" style="width:40px;">
  </a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'website:homepage' %}">Manufacture</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'reporting:homepage' %}">Metrics</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'admin:index' %}" target="_blank" rel="noopener noreferrer">Users & Settings</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'management:stop_cnc' %}">Master CNC Reset</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'core:logout' %}">Logout</a>
    </li>

    <li class="nav-item">
      <a class="fas fa-upload" data-toggle="tooltip" title="Upload Lenses CSV" href="{% url 'management:upload_csv' %}"></a>
      {% if cnc_is_locked %}
        <a class="unlock" href="{% url 'management:toggle_cnc' %}">
          <i class="fas fa-lock"  data-toggle="tooltip" title="Unlock CNC Machine"></i>
          <i class="fas fa-unlock" data-toggle="tooltip" title="Unlock CNC Machine"></i>
        </a>
      {% else %}
        <a class="lock" href="{% url 'management:toggle_cnc' %}">
          <i class="fas fa-unlock"  data-toggle="tooltip" title="Lock CNC Machine"></i>
          <i class="fas fa-lock" data-toggle="tooltip" title="Lock CNC Machine"></i>
        </a>
      {% endif %}
    </li>

  </ul>
</nav>

<script>
  $('.lock .unlock').click(function(){
      window.location.href = "{% url 'management:toggle_cnc' %}";
  });
</script>

website/templates/website/queue_form.html
<form action="{% url 'website:add_to_queue' %}" method="POST">
  {% csrf_token %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
      </div>
    {% endfor %}
    {{ field.label }}
    {{ field }}<br />
  {% endfor %}
  <b>Note: </b> Setting a custom band size will save it as the default band size for the lense.
  <button class="btn btn-success col-12">Add to Queue</button>
</form>

website/templates/website/server_messages.html
<!-- Server Messages to User -->
<div class="row">
  {% block custom_message %} {% endblock custom_message %}
  <div class="col center">
    {% if messages %}
        {% for message in messages %}
            {% if "error" in message.level_tag %}
            <div class="alert alert-danger">
                <text {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {{ message }}
                </text>
            </div>
            {% else %}
            <div class="alert alert-success">
                <text {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {{ message }}
                </text>
            </div>
            {% endif %}
        {% endfor %}
    {% else %}
    <br />
    {% endif %}
  </div>
</div>